# Name of website and author
title: Readme-Workflows
author: Contributors @ Readme-Workflows

safe: true

encoding: "utf-8"
layouts_dir: _layouts
includes_dir: _includes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
